SNOW-933278: Add camelCase, eqeqeq and no-sync rules for eslint
snowflakedb/snowflake-connector-nodejs pull request #662
Opened 2023-10-06 14:36 UTC by sfc-gh-dprzybysz

### Description
- Add camelCase, eqeqeq and no-sync rules for eslint
- Add samples to the directories to lint
- Add script showing only lint errors

### Checklist
- [x] Format code according to the existing code style (run `npm run lint:check -- CHANGED_FILES` and fix problems in changed code)
- [ ] Create tests which fail without the change (if possible)
- [ ] Make all tests (unit and integration) pass (`npm run test:unit` and `npm run test:integration`)
- [ ] Extend the README / documentation and ensure is properly displayed (if necessary)
- [x] Provide JIRA issue id (if possible) or GitHub issue id in commit message

2023-10-09 06:57 UTC, sfc-gh-pmotacki requested changes

2023-10-09 06:57 UTC, sfc-gh-pmotacki commented on .eslintrc.js
> +    'no-sync': ['warn'],
This check is deprecated. I know that it is only warn but I'm bot sure we are ready to add that rule

2023-10-19 07:40 UTC, sfc-gh-pmotacki commented on .eslintrc.js
> +    'no-sync': ['warn'],
We can add it in next iteration

2023-10-19 11:43 UTC, sfc-gh-pfus approved these changes

2023-10-23 08:21 UTC, sfc-gh-pmotacki approved these changes

2023-10-23 08:45 UTC, merged